# Generated by Django 4.2.16 on 2024-11-22 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='symbol',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='uom',
            old_name='symbol',
            new_name='code',
        ),
    ]
