# Generated by Django 4.2.15 on 2024-09-02 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0002_warehouse_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regency',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('alt_name', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regencies', to='InventoryApp.province')),
            ],
        ),
    ]
