# Generated by Django 4.2.16 on 2024-10-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0002_alter_warehouse_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
