# Generated by Django 4.2.15 on 2024-09-02 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0003_regency'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='regency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.regency'),
        ),
    ]
