# Generated by Django 4.2.16 on 2024-10-23 02:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0003_area_active_alter_area_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
