# Generated by Django 4.2.16 on 2024-10-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0004_alter_area_id_alter_warehouse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
