# Generated by Django 4.2.16 on 2024-10-25 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0005_alter_warehouse_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='location',
            new_name='zone',
        ),
    ]
