# Generated by Django 4.2.15 on 2024-09-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0008_alter_district_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='alt_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
