# Generated by Django 4.2.15 on 2024-09-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0012_alter_village_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
